export const ROUTES = {
  REFRESH: "/refresh_token",
  REFRESH_BASE:"/auth",
  AUTH: {
    SUPERADMIN: {
      BASE: "/super_admin",
      LOGIN: "/login",
      LOGOUT: "/logout",
      CREATE_SUBSCRIPTION: "/create_subscription",
      BLOCK_SUBSCRIPTION: "/block_subscription/:subscriptionId",
      UNBLOCK_SUBSCRIPTION: "/unblock_subscription/:subscriptionId",
      FIND_SUBSCRIPTION: "/subscription/:subscriptionId",
      UPDATE_SUBSCRIPTION: "/update_subscription/:subscriptionId",
      LIST_SUBSCRIPTION: "/list_subscription",
      LIST_GYM: "/list_gym",
      BLOCK_GYM: "/block_gyms/:gymId",
      UNBLOCK_GYM: "/unblock_gym/:gymId",
      DETAIL_GYM: "/gym_detail/:gymId",
      APPROVE_GYM: "/gym_approve/:gymId",
      REJECT_GYM: "/gym_reject/:gymId",
    },
  },

  GYMADMIN: {
    BASE: "/gym_admin",
    AUTH: {
      EMAIL_VERIFY: "/verify_email",
      OTP_VERIFY: "/verify_otp",
      SIGNUP: "/signup",
      LOGIN: "/login",
      LOGOUT: "/logout",
    },
    LISTTRAINER: "/list_trainers",
    LIST_ACTIVE_TRAINERS: "/list_active_trainers",
    CREATE_TRAINER: "/create_trainer",
    UPDATE_TRAINER:"/update_trainer/:trainerId",
    FIND_TRAINER:"/find_trainer/:trainerId",
    UNBLOCK_TRAINER:"/unblock_trainer/:trainerId",
    BLOCK_TRAINER:"/block_trainer/:trainerId",
    LISTSUBSCRIPTION: "/list_active_subscription",
    PURCHASESUBSCRIPTION: "/purchase_subscription",
    CREATE_BRANCH: "/create_branch",
    BLOCK_BRANCH: "/block_branch/:branchId",
    UNBLOCK_BRANCH: "/unblock_branch/:branchId",
    FIND_BRANCH: "/branch_detail/:branchId",
    UPDATE_BRANCH: "/update_branch/:branchId",
    LIST_BRANCH: "/list_branch",
    LIST_ACTIVE_BRANCH:"/list_active_branch",
    LISTMEMBER: "/list_member",
    CREATE_MEMBER: "/create_member",
    UPDATE_MEMBER:"/update_member/:memberId",
    FIND_MEMBER:"/find_member/:memberId",
    UNBLOCK_MEMBER:"/unblock_member/:memberId",
    BLOCK_MEMBER:"/block_member/:memberId",
    VIEW_PROFILE:"/gym_admin_profile",
    UPDATE_PROFILE:"/gym_admin_profile_update",
    CHANGE_PASSWORD:"/gym_admin_password_change",
    CREATE_PACKAGE: "/create_package",
    BLOCK_PACKAGE: "/block_package/:packageId",
    UNBLOCK_PACKAGE: "/unblock_package/:packageId",
    FIND_PACKAGE: "/package/:packageId",
    UPDATE_PACKAGE: "/update_package/:packageId",
    LIST_PACKAGE: "/list_package",
  },

  TRAINER: {
    BASE: "/trainer",
    AUTH: {
      EMAIL_VERIFY: "/verify_email",
      OTP_VERIFY: "/verify_otp",
      SIGNUP: "/signup",
      LOGIN: "/login",
      LOGOUT:"/logout"
    },
    ADD_MEMBER: "/add_member",
    LIST_MEMBER: "/list_members",
    LIST_ACTIVE_TRAINER:"/active_trainers",
    VIEW_PROFILE:"/trainer_profile",
    UPDATE_PROFILE:"/trainer_profile_update",
    CHANGE_PASSWORD:"/trainer_password_change",
    MARK_ATTENDANCE:"/mark_attendance",
    CHECK_OUT_ATTENDANCE:"/ckeckout_attendance",
    GET_ATTENDANCE:"/get_attendance",
    GET_ALL_ATTENDANCE:"/get_all_attendance"
  },

  MEMBER: {
    BASE: "/member",
    LOGIN: "/login",
    LOGOUT:"/logout",
    VIEW_PROFILE:"/member_profile",
    UPDATE_PROFILE:"/member_profile_update",
    CHANGE_PASSWORD:"/member_password_change",
    UPLOAD_PROFILE_PICTURE:"/member_profile_picture_upload",
    DELETE_PROFILE_PICTURE:"/member_profile_picture_delete",
  }
};