export const API_ROUTES = {
  AUTH: {
    REFRESH: "/refresh_token",
    BASE:"/auth",
  },
  SUPERADMIN: {
    BASE: "/super_admin",
    LOGIN: "/login",
    LOGOUT: "/logout",
    CREATE_SUBSCRIPTION: "/create_subscription",
    BLOCK_SUBSCRIPTION: "/block_subscription",
    UNBLOCK_SUBSCRIPTION: "/unblock_subscription",
    FIND_SUBSCRIPTION: "/subscription",
    UPDATE_SUBSCRIPTION: "/update_subscription",
    LIST_SUBSCRIPTION: "/list_subscription",
    LIST_GYM: "/list_gym",
    BLOCK_GYM: "/block_gyms",
    UNBLOCK_GYM: "/unblock_gym",
    DETAIL_GYM: "/gym_detail",
    APPROVE_GYM: "/gym_approve",
    REJECT_GYM: "/gym_reject",
  },

  GYMADMIN: {
    BASE: "/gym_admin",
    AUTH: {
      EMAIL_VERIFY: "/verify_email",
      OTP_VERIFY: "/verify_otp",
      SIGNUP: "/signup",
      LOGIN: "/login",
      LOGOUT: "/logout",
    },
    LISTTRAINER: "/list_trainers",
    LIST_ACTIVE_TRAINERS: "/list_active_trainers",
    CREATE_TRAINER: "/create_trainer",
    UPDATE_TRAINER:"/update_trainer",
    FIND_TRAINER:"/find_trainer",
    UNBLOCK_TRAINER:"/unblock_trainer",
    BLOCK_TRAINER:"/block_trainer",
    LISTSUBSCRIPTION: "/list_active_subscription",
    PURCHASESUBSCRIPTION: "/purchase_subscription",
    CREATE_BRANCH: "/create_branch",
    BLOCK_BRANCH: "/block_branch",
    UNBLOCK_BRANCH: "/unblock_branch",
    FIND_BRANCH: "/branch_detail",
    UPDATE_BRANCH: "/update_branch",
    LIST_BRANCH: "/list_branch",
    LIST_ACTIVE_BRANCH:"/list_active_branch",
    LISTMEMBER: "/list_member",
    CREATE_MEMBER: "/create_member",
    UPDATE_MEMBER:"/update_member",
    FIND_MEMBER:"/find_member",
    UNBLOCK_MEMBER:"/unblock_member",
    BLOCK_MEMBER:"/block_member",
    VIEW_PROFILE:"/gym_admin_profile",
    UPDATE_PROFILE:"/gym_admin_profile_update",
    CHANGE_PASSWORD:"/gym_admin_password_change",
    CREATE_PACKAGE: "/create_package",
    BLOCK_PACKAGE: "/block_package",
    UNBLOCK_PACKAGE: "/unblock_package",
    FIND_PACKAGE: "/package",
    UPDATE_PACKAGE: "/update_package",
    LIST_PACKAGE: "/list_package",
  },

  TRAINER: {
    BASE: "/trainer",
    AUTH: {
      EMAIL_VERIFY: "/verify_email",
      OTP_VERIFY: "/verify_otp",
      SIGNUP: "/signup",
      LOGIN: "/login",
      LOGOUT:"/logout",
    },
    ADD_MEMBER: "/add_member",
    LIST_MEMBER: "/list_members",
    LIST_ACTIVE_TRAINER:"/active_trainers",
    VIEW_PROFILE:"/trainer_profile",
    UPDATE_PROFILE:"/trainer_profile_update",
    CHANGE_PASSWORD:"/trainer_password_change",
    MARK_ATTENDANCE:"/mark_attendance",
    CHECK_OUT_ATTENDANCE:"/ckeckout_attendance",
    GET_ATTENDANCE:"/get_attendance",
    GET_ALL_ATTENDANCE:"/get_all_attendance",
    GET_CURRENT_MONTH_ATTENDANCE:"/get_current_month_attendance"
  },
  MEMBER:{
    BASE:"/member",
    LOGIN:"/login",
    LOGOUT:"/logout",
    VIEW_PROFILE:"/member_profile",
    UPDATE_PROFILE:"/member_profile_update",
    CHANGE_PASSWORD:"/member_password_change",
    UPLOAD_PROFILE_PICTURE:"/member_profile_picture_upload",
    DELETE_PROFILE_PICTURE:"/member_profile_picture_delete",
    MARK_ATTENDANCE:"/mark_attendance",
    CHECK_OUT_ATTENDANCE:"/ckeckout_attendance",
    GET_ATTENDANCE:"/get_attendance",
    GET_ALL_ATTENDANCE:"/get_all_attendance",
    GET_CURRENT_MONTH_ATTENDANCE:"/get_current_month_attendance"
  }
};
