export const FRONTEND_ROUTES = {
  LANDING: "/",
  SUBSCRPIPTION: "/subscription",
  GYM_ADMIN: {
    BASE: "/gym-admin",
    SIGNUP: "/signup",
    LOGIN: "login",
    OTP: "/gym-admin/otp-verification",
    DASHBOARD: "dashboard",
    LIST_MEMBERS: "members",
    LIST_EMPLOYEES: "employees",
    DETAIL_EMPLOYEES: "detail-employees",
    LIST_SUBSCRIPTION: "list-subscription",
    LIST_BRANCH: "branches",
    PENDINGAPPROVAL: "approval",
    DETAIL_MEMBER: "detail-member",
    GYM_INFO: "gym-info",
    LIST_PACKAGE: "packages",
    SUCCESS: "success",
    CANCEL: "cancel",
    SUBSCRIPTION: "subscriptions",
    REAPPLY: "reapply",
    LIST_REVENUE: "revenues",
    REVENUE_DETAIL: "revenue_detail",
    LIST_EXPENSE: "expenses",
    PROFIT: "profit_analytics",
    LEAVE: "leaves",
    FORGOT_PASSWORD: "forgot_password",
    SALARY: "salary",
    SALARY_DETAIL: "salary_detail",
    NOT_FOUND:"not_found"
  },
  SUPER_ADMIN: {
    BASE: "/super-admin",
    LOGIN: "login",
    DASHBOARD: "dashboard",
    LIST_SUBSCRIPTION: "subscriptions",
    ADD_SUBSCRIPTION: "add-subscription",
    EDIT_SUBSCRIPTION: "edit-subscription/:id",
    LIST_GYMS: "gyms",
    GYM_DETAIL: "gym-detail/:gymId",
    LIST_PAYMENTS: "payments",
    PAYMENT_DETAIL: "payment_detail",
    NOT_FOUND:"not_found"
  },
  TRAINER: {
    BASE: "/trainer",
    LOGIN: "login",
    DASHBOARD: "dashboard",
    LIST_MEMBERS: "members",
    DETAIL_MEMBER: "detail-member",
    PROFILE: "profile",
    LEAVE: "leaves",
    SESSION: "sessions",
    CHAT: "chat",
    FORGOT_PASSWORD: "forgot_password",
    SALARY: "salary",
    NOT_FOUND:"not_found"
  },
  MEMBER: {
    BASE: "/member",
    LOGIN: "login",
    DASHBOARD: "dashboard",
    PROFILE: "profile",
    PACKAGELIST: "package_list",
    MEMBERSHIP: "packages",
    SUCCESS: "success",
    LIST_PAYMENTS: "payments",
    WORKOUT_PLAN: "workout_plans",
    DIET_PLAN: "diet_plans",
    BOOK_TRAINER: "book_trainer",
    PROGRESS: "progress",
    CHAT: "chat",
    FORGOT_PASSWORD: "forgot_password",
    NOT_FOUND:"not_found"
  },
  NOT_FOUND:"not_found"
};
