export const FRONTEND_ROUTES = {
    LANDING:"/",
    SUBSCRPIPTION:"/subscription",
    GYM_ADMIN: {
        BASE:"/gym-admin",
        SIGNUP:"/signup",
        LOGIN:"login",
        OTP:"/gym-admin/otp-verification",
        DASHBOARD:"dashboard",
        LIST_MEMBERS:"members",
        LIST_EMPLOYEES:"employees",
        LIST_SUBSCRIPTION:"list-subscription",
        LIST_BRANCH:"branches",
        PENDINGAPPROVAL:"approval"
    },
    SUPER_ADMIN:{
        BASE:"/super-admin",
        LOGIN:"login",
        DASHBOARD:"dashboard",
        LIST_SUBSCRIPTION:"subscriptions",
        ADD_SUBSCRIPTION:"add-subscription",
        EDIT_SUBSCRIPTION:"edit-subscription/:id",
        LIST_GYMS:"gyms",
        GYM_DETAIL:"gym-detail/:gymId",
    },
    TRAINER:{
        BASE:"/trainer",
        LOGIN:"login",
        DASHBOARD:"dashboard",
        LIST_MEMBERS:"members",
    },
    MEMBER:{
        BASE:"/member",
        LOGIN:"login",
        DASHBOARD:"dashboard",
    }
}