export enum GymOwnerFeature {
  DASHBOARD = "DASHBOARD",
  BRANCH_MANAGEMENT = "BRANCH_MANAGEMENT",
  TRAINER_MANAGEMENT = "TRAINER_MANAGEMENT",
  MEMBER_MANAGEMENT = "MEMBER_MANAGEMENT",

  SUBSCRIPTION_PLANS = "SUBSCRIPTION_PLANS",
  MEMBER_SUBSCRIPTIONS = "MEMBER_SUBSCRIPTIONS",

  ATTENDANCE_TRACKING = "ATTENDANCE_TRACKING",
  PROGRESS_TRACKING = "PROGRESS_TRACKING",
  DIET_WORKOUT_PLANS = "DIET_WORKOUT_PLANS",

  PAYMENTS = "PAYMENTS",
  INVOICES = "INVOICES",
  
  ANALYTICS = "ANALYTICS",

  NOTIFICATIONS = "NOTIFICATIONS",
  SUPPORT = "SUPPORT",
}
