export const configEnv = {
    PORT:process.env.PORT,
    MONGO_URL:process.env,
    REDIS_URL:process.env.REDIS_URL,
    JWT_SECRET:process.env.JWT_SECRET,
    GOOGLE_MAIL:process.env.GOOGLE_MAIL,
    GOOGLE_APP_PASSWORD:process.env.GOOGLE_APP_PASSWORD,
    ACCESS_TOKEN_EXPIRATION_TIME:process.env.ACCESS_TOKEN_EXPIRATION_TIME,
    REFRESH_TOKEN_EXPIRATION_TIME:process.env.REFRESH_TOKEN_EXPIRATION_TIME,
    REFRESH_TOKEN_SECRECT_KEY:process.env.REFRESH_TOKEN_SECRET_KEY,
    CLOUDINARY_CLOUD_NAME:process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET:process.env.CLOUDINARY_API_SECRET
}